# ---Environment Configs---
env_name: jumanji
observation_attribute : grid
flatten_observation: True
multi_agent : False

scenario:
  name: Snake-v1
  task_name: snake

kwargs: {
  num_rows: 6,
  num_cols: 6,
}
