# ---MLP Dueling DQN Networks---
actor_network:
  pre_torso:
    _target_: stoix.networks.torso.NoisyMLPTorso
    layer_sizes: [256, 256]
    use_layer_norm: False
    activation: silu
  action_head:
    _target_: stoix.networks.dueling.NoisyDistributionalDuelingQNetwork
    layer_sizes: [512]
    use_layer_norm: False
    activation: silu
