# ---MLP DDPG Networks---
actor_network:
  pre_torso:
    _target_: stoix.networks.torso.MLPTorso
    layer_sizes: [64, 64]
    use_layer_norm: False
    activation: relu
  action_head:
    _target_: stoix.networks.heads.DeterministicHead
  post_processor:
    _target_: stoix.networks.postprocessors.ScalePostProcessor

q_network:
  input_layer:
    _target_: stoix.networks.inputs.ObservationActionInput
  pre_torso:
    _target_: stoix.networks.torso.MLPTorso
    layer_sizes: [64, 64]
    use_layer_norm: False
    activation: relu
  critic_head:
    _target_: stoix.networks.heads.ScalarCriticHead
