# ---Environment Configs---
env_name: mpe

scenario:
  name: MPE_simple_v3
  task_name: mpe_simple

add_agent_ids_to_state: False # Adds the agent IDs to the global state.
flatten_observation: True # Flattens the observations.
add_global_state : False # Adds the global state to the observations.

kwargs:
  num_agents : 1
