# --- Defaults FF-SAC ---

total_timesteps: 1e8 # Set the total environment steps.
# If unspecified, it's derived from num_updates; otherwise, num_updates adjusts based on this value.
num_updates: ~ # Number of updates
seed: 0

# --- RL hyperparameters ---
update_batch_size: 1 # Number of vectorised gradient updates per device.
rollout_length: 5 # Number of environment steps per vectorised environment.
epochs: 64 # Number of sgd steps per rollout.
warmup_steps: 256  # Number of steps to collect before training.
buffer_size: 5000000 # size of the replay buffer.
batch_size: 64 # Number of samples to train on per device.
actor_lr: 3e-4  # the learning rate of the policy network optimizer
q_lr: 3e-4  # the learning rate of the Q network network optimizer
alpha_lr: 3e-4  # the learning rate of the alpha optimizer
tau: 0.005  # smoothing coefficient for target networks
gamma: 0.99  # discount factor
autotune: True  # whether to autotune alpha
target_entropy_scale: 2.0  # scale factor for target entropy (when auto-tuning)
init_alpha: 0.1  # initial entropy value when not using autotune
max_grad_norm: 0.5 # Maximum norm of the gradients for a weight update.
decay_learning_rates: True # Whether learning rates should be linearly decayed during training.
