# --- Defaults FF-Sampled-AZ ---

# This is an implementation of Sampled MuZero but using a perfect environment model for the search as in AlphaZero.
# Additionally, the search method used can be chosen between muzero mcts and gumbel mcts from mctx.
# Lastly, this version is designed with a Gaussian policy in mind.

system_name: ff_az # Name of the system.

# --- RL hyperparameters ---
actor_lr: 3e-4 # Learning rate for actor network
critic_lr: 3e-4 # Learning rate for critic network
update_batch_size: 1 # Number of vectorised gradient updates per device.
rollout_length: 8 # Number of environment steps per vectorised environment.
epochs: 8 # Number of epochs per training data batch.
warmup_steps: 64 # Number of steps to collect before training.
buffer_size: 10_000 # Size of the replay buffer.
batch_size: 128 # Number of samples to train on per device.
sample_sequence_length: 6 # Number of steps to consider for each element of the batch.
period : 1 # Period of the sampled sequences.
gamma: 0.99 # Discounting factor.
gae_lambda: 0.95 # Lambda value for GAE computation.
ent_coef: 0.005 # Entropy regularisation term for loss function.
vf_coef: 1.0 # Critic weight in
max_grad_norm: 0.5 # Maximum norm of the gradients for a weight update.
decay_learning_rates: False # Whether learning rates should be linearly decayed during training.
num_simulations: 50 # Number of simulations to run.
max_depth: ~ # Maximum depth of the search tree.
search_method : muzero # Search method to use. Options: gumbel, muzero.
num_samples: 10 # Number of action samples to use in search.
root_exploration_sigma : 0.05 # Noise to add to the root node sampled actions.
